import { db, pool, productsTable } from "@workspace/db";

const products = [
  {
    id: "field-notebook",
    name: "Field Notes No. 04",
    description: "A pocket notebook with a soft-touch cover and 64 pages of fountain-pen friendly paper.",
    priceCents: 1800,
    compareAtPriceCents: null,
    category: "Desk",
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=85",
    badge: "Bestseller",
    inventory: 42,
    featured: true,
  },
  {
    id: "stoneware-mug",
    name: "Studio Stoneware Mug",
    description: "Hand-finished in a quiet sand glaze, with a comfortable thumb rest and generous 12 oz pour.",
    priceCents: 3200,
    compareAtPriceCents: 3800,
    category: "Home",
    imageUrl: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1200&q=85",
    badge: "New",
    inventory: 18,
    featured: true,
  },
  {
    id: "linen-tote",
    name: "Everyday Linen Tote",
    description: "A structured carry-all cut from heavyweight linen with reinforced handles for daily errands.",
    priceCents: 4600,
    compareAtPriceCents: null,
    category: "Carry",
    imageUrl: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=1200&q=85",
    badge: null,
    inventory: 24,
    featured: true,
  },
  {
    id: "desk-lamp",
    name: "Arc Desk Lamp",
    description: "A compact brushed-metal lamp with a warm dimmable glow for late work and early mornings.",
    priceCents: 8900,
    compareAtPriceCents: null,
    category: "Desk",
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=85",
    badge: "Staff pick",
    inventory: 9,
    featured: true,
  },
  {
    id: "wool-throw",
    name: "Merino Travel Throw",
    description: "A light, generous layer in brushed merino wool that belongs on the sofa and in the back seat.",
    priceCents: 11200,
    compareAtPriceCents: null,
    category: "Home",
    imageUrl: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1200&q=85",
    badge: null,
    inventory: 12,
    featured: false,
  },
  {
    id: "ceramic-tray",
    name: "Catchall Ceramic Tray",
    description: "A low-profile tray for keys, rings, and the small things that make a room feel lived in.",
    priceCents: 2800,
    compareAtPriceCents: null,
    category: "Home",
    imageUrl: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=85",
    badge: null,
    inventory: 31,
    featured: false,
  },
];

await db.insert(productsTable).values(products).onConflictDoNothing();
await pool.end();